### ISSUE TITLE
Please Add Website Link Next To Title And Dropbox CDN

### ISSUE THREAD

**Issue by anonyco** [frqnck/apt.js#1]
Next to the description at the top of the page, please add a link to the Test suite. Then, please add a Dropbox CDN link (just like at [my repository here](https://github.com/anonyco/BestBase64EncoderDecoder#quick-start)) so that users can quickly drop the code into their page without having to copy and paste the full 2kb. A CDN link really help out beginners and anti-framework like myself who are confused at complex build system.

**Comment by frqnck** [comment]
Ok. Thanks to you both of these have been added.
